import "./globals.css";

import type { Metadata } from "next";
import StoreProvider from "@/features/ui/StoreProvider";

// Fallback font configuration to avoid network dependency issues
const golos = {
  variable: "--font-golos",
};

export const metadata: Metadata = {
  title: "Smart You",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${golos.variable} antialiased bg-dark font-golos text-white`}
      >
        {children}

        <StoreProvider />
      </body>
    </html>
  );
}
