import "./globals.css";

import { Golos_Text } from "next/font/google";
import type { Metadata } from "next";
import StoreProvider from "@/features/ui/StoreProvider";
import { Web3Provider } from "@/features/model/useWeb3Context";

const golos = Golos_Text({
  variable: "--font-golos",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart You",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${golos.variable} antialiased bg-dark font-golos text-white`}
      >
        <Web3Provider>
          {children}
        </Web3Provider>

        <StoreProvider />
      </body>
    </html>
  );
}
